version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cognito1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jv08kk1xmdf7"
s3_prefix = "cognito1"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
